### ISSUE TITLE
Playground POST body use example button not working

### ISSUE THREAD

**Issue by ghost** [zuplo/zudoku#1030]
As the title says. While using the playground for a POST request I noticed the button does not work at all. I first thought it was specific for some content types (see #1025) but it seems to be in general.

![Image](https://github.com/user-attachments/assets/c382560c-316a-41c4-829d-4d3f042b897e)

**Comment by dan-lee** [comment]
Should be fixed in [v0.46.2](https://github.com/zuplo/zudoku/releases/tag/v0.46.2)!

**Comment by ghost** [comment]
No, it has not. I still cannot use that button. Please re-open this issue.

![Image](https://github.com/user-attachments/assets/b59dc140-11ec-4352-b181-29e58eb9c506).

**Comment by dan-lee** [comment]
Can you provide a reproducible example? In our test example project it looks like it's working: https://www.cosmocargo.dev/api-shipments/rates-and-billing#calculate-shipping-rates

**Comment by victormer** [comment]
> Can you provide a reproducible example? In our test example project it looks like it's working: https://www.cosmocargo.dev/api-shipments/rates-and-billing#calculate-shipping-rates

Hey! Could you please share the API’s openapi.yaml file? I suspect the examples might not be built correctly, and seeing the spec would help clarify. Thanks!

**Comment by dan-lee** [comment]
@victormer You can see all the schemas of this example in this monorepo: https://github.com/zuplo/zudoku/blob/ab6f2529cb90245a3297e9c1e9b5e1e9ebc60916/examples/cosmo-cargo/schema/shipments.json#L1170-L1191

Or [in the directory](https://github.com/zuplo/zudoku/tree/main/examples/cosmo-cargo/schema) directly

**Comment by victormer** [comment]
oh, so 

> [@victormer](https://github.com/victormer) You can see all the schemas of this example in this monorepo:
> 
> [zudoku/examples/cosmo-cargo/schema/shipments.json](https://github.com/zuplo/zudoku/blob/ab6f2529cb90245a3297e9c1e9b5e1e9ebc60916/examples/cosmo-cargo/schema/shipments.json#L1170-L1191)
> 
> Lines 1170 to 1191 in [ab6f252](/zuplo/zudoku/commit/ab6f2529cb90245a3297e9c1e9b5e1e9ebc60916)
> 
>        "examples": { 
>          "basic": { 
>            "summary": "Basic service level", 
>            "value": { 
>              "serviceLevel": "STANDARD" 
>            } 
>          }, 
>          "insured": { 
>            "summary": "Express with insurance", 
>            "description": "Express shipping with insurance for high-value electronics", 
>            "value": { 
>              "serviceLevel": "EXPRESS", 
>              "insurance": { 
>                "value": 1500.0, 
>                "description": "Gaming laptop with accessories" 
>              } 
>            } 
>          } 
>        } 
>      } 
>    } 
>  }, 
> Or [in the directory](https://github.com/zuplo/zudoku/tree/main/examples/cosmo-cargo/schema) directly

@dan-lee oh, so you recommend using json files instead of yaml files?

**Comment by dan-lee** [comment]
> oh, so you recommend using json files instead of yaml files?

@victormer no that should work just fine, we support both :)
(internally we convert the YAML to JSON)

**Comment by victormer** [comment]
@dan-lee cool, for me it's working with the example you provided. Thanks!

@rlkasparsolutions check it out.
