### ISSUE TITLE
Test button in local

### ISSUE THREAD

**Issue by majoshi1** [zuplo/zudoku#260]
Nothing happens when I click on Test button in [local](http://localhost:9000/api#pet-finds-pets-by-status-find-pets-by-status). But it works fine in [live demo](https://zudoku.dev/demo?api-url=https%3A%2F%2Fzudoku.dev%2Fpetstore.oas.json#pet-finds-pets-by-status-find-pets-by-status). Any idea?

OS: Windows 10.
Client: Git Bash

Tried with both `npm create zudoku-app@latest` & `git clone https://github.com/zuplo/zudoku.git`

**Comment by dan-lee** [comment]
As far as I can tell this issue is only apparent on Windows. What you see is the server-side rendered output. The client-side bundle cannot be loaded because of a permission error I see in the console:

> Not allowed to load local resource: file:///C:/Users/Dan/dev/zudoku/packages/zudoku/src/app/entry.client.tsx

We load the entry point from the absolute path, which works on macOS but apparently doesn't under Windows

I need to investigate further how to solve this, happy for suggestions though.

**Comment by dan-lee** [comment]
@majoshi1 @muke78 I have thought of a fix in PR #264.
Can you temporarily install the pre-release version `zudoku@0.0.0-76bbec5` in your `package.json` to see if this resolves your issue?

**Comment by majoshi1** [comment]
With `zudoku@0.0.0-76bbec5`, the Test button now started showing popup. Thanks for the quick fix.

PS: There is an error on console. Not sure if we need to fix them.
```

🚀 Zudoku Portal: http://localhost:9000

8:48:56 AM zudoku Pre-transform error: Failed to load url /__z/entry.client.tsx (resolved id: /__z/entry.client.tsx). Does the file exist?

```

**Comment by dan-lee** [comment]
@majoshi1 thanks for reporting back! I fixed that as well, it's now released in https://github.com/zuplo/zudoku/releases/tag/v0.13.0

**Comment by arian0zen** [comment]
@dan-lee this issue still persists.. stuck on this for a couple of hours now! 
![image](https://github.com/user-attachments/assets/951aef04-d183-439d-a8e1-31d5fafbf0a2)
this the entry.client.tsx for me.. is it supposed to be empty like this ?

**Comment by arian0zen** [comment]
zudoku@0.0.0-76bbec5 this version works as expected but @0.13.3 does not seem to work!

**Comment by arian0zen** [comment]
I have thought of a fix and added a PR #288  @dan-lee
